version: '3'
services:
  backend:
    build:
      context: ./edtech-backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
      - "3000:3000"
    container_name: test-backend
    volumes:
      - ./edtech-backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", '-t', '30', "mysql:3306", "--", "npm", "start"]
  frontend:
    build:
      context: ./edtech-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: test-frontend
    volumes:
      - ./edtech-frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
    depends_on:
      - backend
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    container_name: test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: edtech_db